version: '3.8'

services: 
    postgres: 
        image: postgres
        networks: 
            - mattermost_network
        env_file: .env
        restart: 'always'
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init-user-db/postgresql/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
    # mysql: 
    #     image: mysql
    #     command: --default-authentication-plugin=mysql_native_password
    #     networks: 
    #         - mattermost_network
    #     env_file: .env
    #     restart: 'always'
    #     ports:
    #         - 3306:3306
    #     volumes:
    #         - mysql_data:/var/lib/mysql
    #         - ./init-user-db/mysql/init-user-db.sql:/docker-entrypoint-initdb.d/init-user-db.sql:ro
    s3:
        image: minio/minio
        environment:
          MINIO_ROOT_USER: minio
          MINIO_ROOT_PASSWORD: minio123
        command: server /data
        volumes:
            - s3_data:/data
        networks: 
            - mattermost_network
        restart: 'always'
        ports:
            - 9000:9000
    smtp:
        image: mailhog/mailhog
        ports:
            - 1025:1025
            - 8025:8025
    mattermost:
        build: .
        networks: 
            - mattermost_network
        volumes: 
            - .:/buildpack
            - cache:/cache
            - build:/build
            - env:/env
            - app:/app
        env_file: .env
        ports: 
            - 8065:8065
        depends_on:
            - postgres
            # - mysql
volumes: 
    postgres_data:
    mysql_data:
    cache:
    build:
    env:
    app:
    s3_data:
networks: 
    mattermost_network: